name: Release Action

on:
  release:
    types:
      - published

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN_COMMIT }}

jobs:
  publish-package:
    runs-on: ubuntu-latest
    name: Publish to NPM

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: '3.x'
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_COMMIT }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install packages
        run: npm install

      - name: Install typescript
        run: npm install -g typescript

      - name: Publish to NPM
        run: ./scripts/publish.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  update-release-notes:
    runs-on: ubuntu-latest
    name: Update Release Notes

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: '3.x'
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_COMMIT }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Update RELEASES.MD
        uses: vonage/generate-release-log@1.0.2

      - name: Commit release notes
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add RELEASES.md
          git commit -m "chore: updated release log"
          git push --force-with-leaseCallUpdateResultc

  build-wiki-documentation:
    name: Build Wiki Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: '3.x'
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_COMMIT }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install packages
        run: npm install

      - name: Install typescript
        run: npm install -g typescript

      - name: Build Typescript
        run: npm run compile

      - name: Build Typedoc
        run: npm run typedoc

      - name: Update markdown files
        run: |
          cd docs
          ../scripts/adjustMarkdown.sh

      - name: Build example markdown
        run: node scripts/generateExample.mjs

      - name: Final Adjustment to files
        run: |
          mv docs/packages.md docs/HOME.md
          mv docs/EXAMPLES.md .
          rm -rf docs/index.md docs/docs.json

      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@main
        with:
          source: docs
          destination: wiki
          token: ${{ secrets.GH_TOKEN_COMMIT}}
          gitAuthorName: github-actions
          gitAuthorEmail: github-actions@github.com
          branch: main

  notify-release:
    runs-on: ubuntu-latest
    name: Notify Release
    steps:
      - name: Post to DevRel Private
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_DEVREL_PRIVATE_URL }}
          webhook-type: incoming-webhook
          errors: true
          payload: |
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: ":initial_external_notification_sent: Version ${{ github.event.release.name }} of the NodeJS SDK has been released"
              - type: "section"
                text:
                  type: "plain_text"
                  text: "${{ github.event.release.body }}"
                  emoji: true
              - type: "divider"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "You can view the full change log <${{github.event.release.html_url }}|here>"

      - name: Post to DevRel Tooling
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_DEVREL_TOOLING_URL }}
          webhook-type: incoming-webhook
          errors: true
          payload: |
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: ":initial_external_notification_sent: Version ${{ github.event.release.name }} of the NodeJS SDK has been released"
              - type: "section"
                text:
                  type: "plain_text"
                  text: "${{ github.event.release.body }}"
                  emoji: true
              - type: "divider"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "You can view the full change log <${{github.event.release.html_url }}|here>"

      - name: Post to Ask DevRel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_ASK_DEVREL_URL }}
          webhook-type: incoming-webhook
          errors: true
          payload: |
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: ":initial_external_notification_sent: Version ${{ github.event.release.name }} of the NodeJS SDK has been released"
              - type: "section"
                text:
                  type: "plain_text"
                  text: "${{ github.event.release.body }}"
                  emoji: true
              - type: "divider"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "You can view the full change log <${{github.event.release.html_url }}|here>"
